version: '3'
services:
  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3002:3002"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: yarn start:dev
    env_file:
      - .env
    environment:
      - PORT=3002

  users_microservice:
    build: ./users-microservice
    ports:
      - "5555:5555"
    volumes:
      - ./users-microservice/src:/usr/src/app/src
      - ./users-microservice/prisma:/usr/src/app/prisma
    command: yarn start:dev
    depends_on:
      - postgres_db_users
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_db_application:5432/application_db

  application_microservice:
    build: ./application-microservice
    ports:
      - "5556:5556"
    volumes:
      - ./application-microservice/src:/usr/src/app/src
      - ./application-microservice/prisma:/usr/src/app/prisma
    command: "yarn start:dev"
    depends_on:
      - postgres_db_application
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_db_users:5432/application_db

  nats:
    image: nats
    ports:
      - 4222:4222

  postgres_db_users:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata_users:/var/lib/postgresql/data

  postgres_db_application:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata_application:/var/lib/postgresql/data

volumes:
  pgdata_users:
  pgdata_application:
